### ISSUE TITLE
Issue with Hiding in Dock + Changing Keyboard Shortcut

### ISSUE THREAD

**Issue by andrewcincotta** [TetsuakiBaba/quickGPT#2]
I have recently created a fork [here](https://github.com/andrewcincotta/quickGPT-Always-Dark.git) that forces dark mode on quickGPT and its working nicely. I thought I'd be done with my project and deleted my old version, and now I am having trouble hiding quickGPT from the dock as well as changing the toggle window keyboard shortcut. Was this not something we could do in the past? I tried installing your latest release and am still having trouble figuring out how to do these things.

**Comment by andrewcincotta** [comment]
Update: Could it be that I have confused your repo with [this one](https://sindresorhus.gumroad.com/l/quickgpt)? If that's the case, it'd be nice to add the ability to hide the window in the dock, remember size/position, and change the toggle shortcut.

**Comment by TetsuakiBaba** [comment]
> I have recently created a fork [here](https://github.com/andrewcincotta/quickGPT-Always-Dark.git) that forces dark mode on quickGPT and its working nicely. I thought I'd be done with my project and deleted my old version, and now I am having trouble hiding quickGPT from the dock as well as changing the toggle window keyboard shortcut. Was this not something we could do in the past? I tried installing your latest release and am still having trouble figuring out how to do these things.

Hi, Thanks for bringing this to my attention in a great place. I have reflected it in the latest version (v1.1.5).

**Comment by TetsuakiBaba** [comment]
> Update: Could it be that I have confused your repo with [this one](https://sindresorhus.gumroad.com/l/quickgpt)? If that's the case, it'd be nice to add the ability to hide the window in the dock, remember size/position, and change the toggle shortcut.

-  hide the window in the dock: done (v1.1.5)
- remember size/position: I believe that UI design should be displayed at the mouse cursor position. Previously, I had to remember the position, but there was a problem that it took time to find it even if it was displayed at the same position.
- change the toggle shortcut: It is understandable that you would like this feature. Please give me a little time to implement the functionality. control+shift+Q is a combination that can be done with only the left hand, so I recommend it, but for the time being, you can use the following in main.js
globalShortcut.register('Control+Shift+Q', () => {
        toggleWindow();
    })
and you can change it to any shortcut you like.

**Comment by andrewcincotta** [comment]
> > Update: Could it be that I have confused your repo with [this one](https://sindresorhus.gumroad.com/l/quickgpt)? If that's the case, it'd be nice to add the ability to hide the window in the dock, remember size/position, and change the toggle shortcut.
> 
> * hide the window in the dock: done (v1.1.5)
> * remember size/position: I believe that UI design should be displayed at the mouse cursor position. Previously, I had to remember the position, but there was a problem that it took time to find it even if it was displayed at the same position.
> * change the toggle shortcut: It is understandable that you would like this feature. Please give me a little time to implement the functionality. control+shift+Q is a combination that can be done with only the left hand, so I recommend it, but for the time being, you can use the following in main.js
>   globalShortcut.register('Control+Shift+Q', () => {
>   toggleWindow();
>   })
>   and you can change it to any shortcut you like.

Wow, really added these changes quickly! I'll see what I can do about the window position and keyboard shortcut.

**Comment by TetsuakiBaba** [comment]
@andrewcincotta one more thing, 

> Could it be that I have confused your repo with [this one](https://sindresorhus.gumroad.com/l/quickgpt)?

this repo is irrelevant to my quickGPT repository.  I may have to think about re-naming it.

**Comment by andrewcincotta** [comment]
> @andrewcincotta one more thing,
> 
> > Could it be that I have confused your repo with [this one](https://sindresorhus.gumroad.com/l/quickgpt)?
> 
> this repo is irrelevant to my quickGPT repository. I may have to think about re-naming it.

I think you're all good, your version is better! I am going to commit my changes. I do not expect you to publish them, but you could definitely give a look at what I did for centering the window (so that in a future version it could be a setting to toggle between)!

**Comment by andrewcincotta** [comment]
@TetsuakiBaba I ended up creating a new fork with some proposed changes (and will continue to do so). I do not have much experience using Electron and NPM, but the last project I worked on (a [Raycast extension](https://github.com/andrewcincotta/copyq-raycast)) used `npm install && npm run dev` to develop the project. Upon saving the code, the extension would refresh with the desired changes. Is there a way to do this for your project? Right now, whenever I make a change, I have to Control+C the running `npm start` command, and then run it again. Any ideas?

**Comment by TetsuakiBaba** [comment]
@andrewcincotta Hi, 
For electron, I recommend that you use electron-reload. Add a few lines of code and it will automatically restart when the main process or renderer process code changes.

```
npm install electron-reload
```

add this code to the top of main.js
```
require('electron-reload')(__dirname, {
    electron: require(`${__dirname}/node_modules/electron`)
});
```

have a fun.
